name: CI/CD Pipeline

on: [push, pull_request]

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      
    # ----- config git secret scanning -----
      - name: Set up environment variables
        run: |
          echo "GEMINI=${{ secrets.GEMINI }}" >> $GITHUB_ENV
          echo "MONGO_URL=${{ secrets.MONGO_URL }}" >> $GITHUB_ENV

      - name: Install dependencies
        run: npm ci

      - name: Build the app
        run: npm run build

      # ----- SECURITY CHECKS -----

      - name: Audit dependencies
        run: npm audit --audit-level=high || true

      - name: Semgrep static security scan
        uses: returntocorp/semgrep-action@v1
        with:
          config: "p/ci"

      - name: Secret scanning with Gitleaks
        uses: gitleaks/gitleaks-action@v2

      # - name: Check for Security Headers
      #   run: |
      #     curl -s -D - https://class-job-seeker.vercel.app/ -o /dev/null | grep -E 'Content-Security-Policy|X-Frame-Options|X-Content-Type-Options'
      
      
      # - name: Run OWASP ZAP Passive Scan
      #   uses: zaproxy/action-baseline@v0.11.0
      #   with:
      #     target: 'https://class-job-seeker.vercel.app'
      #     issue_title: '' # not giving github permissions
